/**
 * The narrow data-access contract used by every feature.
 *
 * It intentionally mirrors the subset of the Supabase JS client that the PMS
 * relies on. Two implementations satisfy it:
 *
 *   - `supabaseAdapter` — the real client, backed by Postgres + RLS.
 *   - `mockClient`      — an in-memory implementation for local demos/tests.
 *
 * Because both satisfy the same interface, features never branch on the
 * environment and never talk to Supabase directly.
 */

import type { AppError } from './errors'
import type { DatabaseSchema, TableName } from '@/types/database'

/* ------------------------------------------------------------------ */
/* Responses                                                           */
/* ------------------------------------------------------------------ */

export interface ListResponse<T> {
  data: T[] | null
  error: AppError | null
  count: number | null
}

export interface SingleResponse<T> {
  data: T | null
  error: AppError | null
}

export interface UnitResponse {
  error: AppError | null
}

/* ------------------------------------------------------------------ */
/* Filters                                                             */
/* ------------------------------------------------------------------ */

export type FilterValue = string | number | boolean | null | string[] | number[]
export type OrderDirection = { ascending: boolean; nullsFirst?: boolean }
export type Row = Record<string, unknown>

type IsNullable<T> = [null] extends [T] ? true : false

/** Columns whose type includes `null` become optional on write. */
type OptionalizeNullable<T> = {
  [K in keyof T as IsNullable<T[K]> extends true ? never : K]: T[K]
} & {
  [K in keyof T as IsNullable<T[K]> extends true ? K : never]?: T[K]
}

/** `*_at` columns are generated by the database. */
type TimestampKeys<T> = { [K in keyof T]: K extends `${string}_at` ? K : never }[keyof T]

type GeneratedKeys<T> = Extract<'id' | TimestampKeys<T>, keyof T>

export type Insertable<T> = OptionalizeNullable<Omit<T, GeneratedKeys<T>>> &
  Partial<Pick<T, GeneratedKeys<T>>>

export type Updatable<T> = {
  [K in keyof T]?: T[K]
}

export interface SelectOptions {
  count?: 'exact' | 'planned' | 'estimated'
  head?: boolean
}

export interface JoinHint {
  table: string
  columns: string
  relationship: string
}

/* ------------------------------------------------------------------ */
/* Builders                                                            */
/* ------------------------------------------------------------------ */

export interface SelectBuilder<T, R = ListResponse<T>> extends PromiseLike<R> {
  select(columns?: string, options?: SelectOptions): SelectBuilder<T, R>
  eq(column: string, value: unknown): SelectBuilder<T, R>
  neq(column: string, value: unknown): SelectBuilder<T, R>
  gt(column: string, value: unknown): SelectBuilder<T, R>
  gte(column: string, value: unknown): SelectBuilder<T, R>
  lt(column: string, value: unknown): SelectBuilder<T, R>
  lte(column: string, value: unknown): SelectBuilder<T, R>
  like(column: string, pattern: string): SelectBuilder<T, R>
  ilike(column: string, pattern: string): SelectBuilder<T, R>
  in(column: string, values: readonly unknown[]): SelectBuilder<T, R>
  is(column: string, value: null | boolean): SelectBuilder<T, R>
  contains(column: string, value: string | readonly string[]): SelectBuilder<T, R>
  overlaps(column: string, values: readonly unknown[]): SelectBuilder<T, R>
  or(filters: string): SelectBuilder<T, R>
  filter(column: string, operator: string, value: unknown): SelectBuilder<T, R>
  order(column: string, options?: OrderDirection | boolean): SelectBuilder<T, R>
  limit(count: number): SelectBuilder<T, R>
  range(from: number, to: number): SelectBuilder<T, R>
  throwOnError(): SelectBuilder<T, R>
  single(): SelectBuilder<T, SingleResponse<T>>
  maybeSingle(): SelectBuilder<T, SingleResponse<T>>
}

/**
 * Writes share the filter chain with reads; only the resolved shape differs.
 * That mirrors Supabase: `.update(v).eq('id', id).select()` returns rows.
 */
export interface TableRef<T> {
  select(columns?: string, options?: SelectOptions): SelectBuilder<T>
  insert(values: Insertable<T> | Insertable<T>[]): SelectBuilder<T, UnitResponse>
  insert(values: Insertable<T> | Insertable<T>[], options: { count?: 'exact' }): SelectBuilder<T, UnitResponse>
  update(values: Updatable<T>): SelectBuilder<T, UnitResponse>
  upsert(values: Insertable<T> | Insertable<T>[], options?: { onConflict?: string }): SelectBuilder<T, UnitResponse>
  delete(): SelectBuilder<T, UnitResponse>
}

/* ------------------------------------------------------------------ */
/* Auth                                                                */
/* ------------------------------------------------------------------ */

export interface AuthUser {
  id: string
  email: string | null
  emailConfirmedAt: string | null
  userMetadata: Record<string, unknown>
  createdAt: string
}

export interface AuthSession {
  user: AuthUser
  accessToken: string
  expiresAt: number
}

export interface AuthStateResult<T> {
  data: T
  error: AppError | null
}

export type AuthEvent = 'SIGNED_IN' | 'SIGNED_OUT' | 'TOKEN_REFRESHED' | 'USER_UPDATED' | 'INITIAL'

export interface Subscription {
  unsubscribe(): void
}

export interface AuthApi {
  signUp(params: {
    email: string
    password: string
    options?: { data?: Record<string, unknown>; emailRedirectTo?: string }
  }): PromiseLike<AuthStateResult<{ user: AuthUser | null; session: AuthSession | null }>>
  signInWithPassword(params: {
    email: string
    password: string
  }): PromiseLike<AuthStateResult<{ user: AuthUser | null; session: AuthSession | null }>>
  signOut(): PromiseLike<{ error: AppError | null }>
  getUser(): PromiseLike<AuthStateResult<AuthUser | null>>
  getSession(): PromiseLike<AuthStateResult<AuthSession | null>>
  updateUser(attributes: {
    email?: string
    password?: string
    data?: Record<string, unknown>
  }): PromiseLike<AuthStateResult<AuthUser | null>>
  resetPasswordForEmail(
    email: string,
    options?: { redirectTo?: string },
  ): PromiseLike<{ error: AppError | null }>
  onAuthStateChange(
    callback: (event: AuthEvent, session: AuthSession | null) => void,
  ): Subscription
}

/* ------------------------------------------------------------------ */
/* Storage                                                             */
/* ------------------------------------------------------------------ */

export interface UploadResult {
  path: string
  error: AppError | null
}

export interface StorageBucket {
  upload(
    path: string,
    file: File | Blob,
    options?: { contentType?: string; upsert?: boolean },
  ): Promise<UploadResult>
  remove(paths: string[]): PromiseLike<{ error: AppError | null }>
  getPublicUrl(path: string): { data: { publicUrl: string } }
  createSignedUrl(path: string, expiresIn: number): PromiseLike<{
    data: { signedUrl: string } | null
    error: AppError | null
  }>
}

export interface StorageApi {
  from(bucket: string): StorageBucket
}

/* ------------------------------------------------------------------ */
/* Realtime                                                            */
/* ------------------------------------------------------------------ */

export type RealtimeStatus = 'SUBSCRIBED' | 'CHANNEL_ERROR' | 'TIMED_OUT' | 'CLOSED'

export interface RealtimeChannel {
  on(
    event: 'postgres_changes' | 'broadcast',
    filter: { event?: string; schema?: string; table?: string; filter?: string },
    callback: (payload: unknown) => void,
  ): RealtimeChannel
  subscribe(callback?: (status: RealtimeStatus) => void): RealtimeChannel
  unsubscribe(): PromiseLike<{ error: AppError | null }>
}

export interface RealtimeApi {
  channel(name: string, options?: { config?: Record<string, unknown> }): RealtimeChannel
  removeChannel(channel: RealtimeChannel): PromiseLike<{ error: AppError | null }>
}

/* ------------------------------------------------------------------ */
/* Client                                                              */
/* ------------------------------------------------------------------ */

export interface DatabaseClient {
  from<K extends TableName>(table: K): TableRef<DatabaseSchema[K]>
  auth: AuthApi
  storage: StorageApi
  realtime: RealtimeApi
}

export interface ClientOptions {
  /** When true the client records activity/notification side effects locally. */
  readonly mode: 'supabase' | 'demo'
}

export type { AppError }